<?php

/* Bootstrap! */
require dirname( dirname( __DIR__ ) ) . DIRECTORY_SEPARATOR . 'bootstrap.php';


/**
 * Test class for DunEnvironment.
 * Generated by PHPUnit on 2013-10-18 at 16:52:35.
 */
class DunEnvironmentTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var DunEnvironment
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new DunEnvironment;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers DunEnvironment::defines
     * @todo Implement testDefines().
     */
    public function testDefines()
    {
    	$this->object->defines();
    	
    	if ( BAMBOO ) {
    		$this->assertTrue( DUN_PATH == '/home/jwhmcsco/public_html/hosting/includes/dunamis/' );
    		$this->assertFalse( DUN_OS_ISWIN );
    	}
    	else {
    		$this->assertTrue( DUN_PATH == ROOTDIR . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'dunamis' . DIRECTORY_SEPARATOR );
	        $this->assertTrue( DUN_OS_ISWIN );
    	}
    }
}
?>
