<?php

require_once dirname( dirname( dirname( __DIR__ ) ) ) . DIRECTORY_SEPARATOR . 'dunamis' . DIRECTORY_SEPARATOR . 'core' . DIRECTORY_SEPARATOR . 'object.php';


/**
 * Test class for DunObject.
 * Generated by PHPUnit on 2013-10-13 at 20:27:56.
 */
class DunObjectTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var DunObject
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new DunObject;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
?>
