<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2015-11-13 at 22:21:24.
 */
class DunDatabaseTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var DunDatabase
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    	$options	=	array(
    		'hostname'	=>	'localhost',
    		'username'	=>	'root',
    		'password'	=>	'',
    		'database'	=>	'mods_test',
    	);
    	
    	get_dunamis();
    	$this->object = dunloader( 'database', false, $options );
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() { }

    /**
     * @covers DunDatabase::setQuery
     * @todo   Implement testSetQuery().
     */
    public function testSetQuery()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DunDatabase::getAffectedRows
     * @todo   Implement testGetAffectedRows().
     */
    public function testGetAffectedRows()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DunDatabase::getEscaped
     * @todo   Implement testGetEscaped().
     */
    public function testGetEscaped()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DunDatabase::getInsertid
     * @todo   Implement testGetInsertid().
     */
    public function testGetInsertid()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DunDatabase::getInstance
     * @todo   Implement testGetInstance().
     */
    public function testGetInstance()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DunDatabase::getNumRows
     * @todo   Implement testGetNumRows().
     */
    public function testGetNumRows()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DunDatabase::isConnected
     */
    public function testIsConnected()
    {
    	$result	=	$this->object->isConnected();
    	$this->assertTrue( $result, 'Database is connected' );
    }

    /**
     * @covers DunDatabase::loadAssoc
     * @todo   Implement testLoadAssoc().
     */
    public function testLoadAssoc()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DunDatabase::loadAssocList
     * @todo   Implement testLoadAssocList().
     */
    public function testLoadAssocList()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DunDatabase::loadObject
     * @todo   Implement testLoadObject().
     */
    public function testLoadObject()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DunDatabase::loadObjectList
     * @todo   Implement testLoadObjectList().
     */
    public function testLoadObjectList()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DunDatabase::loadResult
     * @todo   Implement testLoadResult().
     */
    public function testLoadResult()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DunDatabase::loadResultArray
     * @todo   Implement testLoadResultArray().
     */
    public function testLoadResultArray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DunDatabase::loadResultList
     * @todo   Implement testLoadResultList().
     */
    public function testLoadResultList()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DunDatabase::loadRow
     * @todo   Implement testLoadRow().
     */
    public function testLoadRow()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DunDatabase::loadRowList
     * @todo   Implement testLoadRowList().
     */
    public function testLoadRowList()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DunDatabase::nameQuote
     * @todo   Implement testNameQuote().
     */
    public function testNameQuote()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DunDatabase::parseFile
     * @todo   Implement testParseFile().
     */
    public function testParseFile()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DunDatabase::query
     * @todo   Implement testQuery().
     */
    public function testQuery()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DunDatabase::Quote
     * @todo   Implement testQuote().
     */
    public function testQuote()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DunDatabase::setError
     * @todo   Implement testSetError().
     */
    public function testSetError()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
