<?php

/**
 * Debug Bar: panel "dumps" template.
 *
 * This file is part of the Tracy (http://tracy.nette.org)
 * Copyright (c) 2004 David Grudl (http://davidgrudl.com)
 */

namespace Tracy;

use Tracy;
$i		=	0;
$cnt	=	1;
?>
<style class="tracy-debug">

	#tracy-debug .tracy-DumpPanel h2 {
		font: 11pt/1.5 sans-serif;
		margin: 0;
		padding: 2px 8px;
		background: #3484d2;
		color: white;
	}

	#tracy-debug .tracy-DumpPanel table {
		width: 100%;
	}
	
	#tracy-debug .tracy-panel table tr.select {
		background-color: #B4FFAD;
	}
	#tracy-debug .tracy-panel table tr.update {
		background-color: #FFE7AD;
	}
	#tracy-debug .tracy-panel table tr.delete {
		background-color: #FFD8D8;
	}
	#tracy-debug .tracy-panel tr:nth-child(2n) td {
		background: linear-gradient( rgba(0, 0, 0, 0.1), rgba(0, 0, 0, 0.1) ) !important;
	}
	#tracy-debug .tracy-panel .args .key { width: 20%; text-align: right; padding-right: 4px; font-weight: bold; display: block; float: left; }
	#tracy-debug .tracy-panel .args .value { float: left; }
	#tracy-debug .tracy-panel .args .clr { clear: both; }
</style>


<h1>Database Queries</h1>

<div class="tracy-inner tracy-DumpPanel">

<table>
<?php foreach ($this->data as $item): ?>
<?php 

$args	=	null;
foreach ( $item['args'] as $k => $v ) {
	$args	.=	"<div class='key'>{$k}</div><div class='value'>{$v}</div><div class='clr'></div>";
}
?>
	<?php $class	=	( strpos( $item['dump'], "SELECT" ) !== false ? 'select' : ( strpos( $item['dump'], "UPDATE" ) !== false ? 'update' : ( strpos( $item['dump'], "DELETE" ) !== false ? 'delete' : 'info' ) ) ); ?>
	<tr class="<?php echo $i++ % 2 ? 'tracy-alt' : '' ?> <?php echo $class ?>">
		<td rowspan="2" width="15"><?php echo $cnt++ ?>) </td><td><?php echo $item['dump'] ?></td>
	</tr>
	<tr class="<?php echo $i++ % 2 ? 'tracy-alt' : '' ?> <?php echo $class ?>">
		<td class="args"><?php echo $args; ?></td>
	</tr>
<?php endforeach ?>
</table>
</div>
