<?php

/**
 * Debug Bar: panel "dumps" template.
 *
 * This file is part of the Tracy (http://tracy.nette.org)
 * Copyright (c) 2004 David Grudl (http://davidgrudl.com)
 */

namespace Tracy;

use Tracy;


$i		=	0;
$cnt	=	1;
?>
<style class="tracy-debug">

	#tracy-debug .tracy-DumpPanel h2 {
		font: 11pt/1.5 sans-serif;
		margin: 0;
		padding: 2px 8px;
		background: #3484d2;
		color: white;
	}

	#tracy-debug .tracy-DumpPanel table {
		width: 100%;
	}
	
	#tracy-debug .tracy-panel table tr.select {
		background-color: #B4FFAD;
	}
	#tracy-debug .tracy-panel table tr.update {
		background-color: #FFE7AD;
	}
	#tracy-debug .tracy-panel table tr.delete {
		background-color: #FFD8D8;
	}
	#tracy-debug .tracy-panel tr:nth-child(2n) td {
		background: linear-gradient( rgba(0, 0, 0, 0.1), rgba(0, 0, 0, 0.1) ) !important;
	}
	
	#tracy-debug-panel-Tracy-ApiBarPanel.tracy-mode-float {
		max-width: 100%;
		width: 75%;
	}
	#tracy-debug-panel-Tracy-ApiBarPanel.tracy-mode-float .tracy-inner.tracy-DumpPanel {
		max-width: 100%;
	}
</style>


<h1>API Requests</h1>

<div class="tracy-inner tracy-DumpPanel">

<table>
<?php foreach ($this->data as $item): ?>
	<?php $class	=	'success'; ?>
	<tr class="<?php echo $i++ % 2 ? 'tracy-alt' : '' ?> <?php echo $class ?>">
		<td width="15"><?php echo $cnt++ ?>) </td><td>
		<td width="25"><?php echo $item['method'] ?></td>
		<td><?php echo $item['call'] ?></td>
		<td>
			<a href="#post<?php echo $i?>" class="tracy-toggle-collapsed">Variables</a><div style="display: none; " id="post<?php echo $i ?>"><pre><?php echo print_r($item['post'],1) ?></pre></div>
			<a href="#optn<?php echo $i?>" class="tracy-toggle-collapsed">Curl Options</a><div style="display: none; " id="optn<?php echo $i ?>"><pre><?php echo print_r($item['optns'],1) ?></pre></div>
		</td>
		<td>
			<a href="#result<?php echo $i?>" class="tracy-toggle-collapsed">Response</a><div style="display: none; " id="result<?php echo $i ?>"><?php echo ( is_bool( $item['result'] ) ? var_dump( $item['result'] ) : $item['result'] ) ?></div>
		</td>
		<td>
			<a href="#curl<?php echo $i?>" class="tracy-toggle-collapsed">Curl Info</a><div style="display: none; " id="curl<?php echo $i ?>"><pre><?php echo print_r($item['curlinfo'],1) ?></pre></div>
		</td>
	</tr>
<?php endforeach ?>
</table>
</div>
