<?php

/**
 * Debug Bar: tab "dumps" template.
 *
 * This file is part of the Tracy (http://tracy.nette.org)
 * Copyright (c) 2004 David Grudl (http://davidgrudl.com)
 */

namespace Tracy;

use Tracy;

if (empty($this->data)) {
	return;
}
?>
<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAEhQTFRFo6Oj////oaGho6Ojqqqqra2tw8PDxcXF0tLS1tbW2dnZ2tra3d3d39/f4ODg5ubm6urq7u7u8PDw8vLy9/f3+Pj4+vr6/Pz87mk6EwAAAAJ0Uk5TAAB2k804AAAANklEQVQY02NgZGBGAgyMDIzMAsKi4uIiQvw8nFy8zCABDj4hMVFBbjZWJhZ2IgVQwGA2FM37AGjxCBmezOkoAAAAAElFTkSuQmCC" /> <?php echo count( $this->data ) . ' quer' . ( count( $this->data ) > 1 ? 'ies' : 'y' ) ?>
