<?php

/**
 * Debug Bar: panel "dumps" template.
 *
 * This file is part of the Tracy (http://tracy.nette.org)
 * Copyright (c) 2004 David Grudl (http://davidgrudl.com)
 */

namespace Tracy;

use Tracy;


$i		=	0;
$cnt	=	1;
?>
<style class="tracy-debug">

	#tracy-debug .tracy-DumpPanel h2 {
		font: 11pt/1.5 sans-serif;
		margin: 0;
		padding: 2px 8px;
		background: #3484d2;
		color: white;
	}

	#tracy-debug .tracy-DumpPanel table {
		width: 100%;
	}
	
	#tracy-debug .tracy-panel table tr.select {
		background-color: #B4FFAD;
	}
	#tracy-debug .tracy-panel table tr.update {
		background-color: #FFE7AD;
	}
	#tracy-debug .tracy-panel table tr.delete {
		background-color: #FFD8D8;
	}
	#tracy-debug .tracy-inner table tr:nth-child(2n) td {
		background: none !important;
	}
	
	#tracy-debug .tracy-inner table tr.tracy-alt {
		background: linear-gradient( rgba(0, 0, 0, 0.04), rgba(0, 0, 0, 0.04) ) !important;
	}
	
	#tracy-debug-panel-Tracy-ApiBarPanel.tracy-mode-float {
		max-width: 100%;
		width: 75%;
	}
	#tracy-debug-panel-Tracy-ApiBarPanel.tracy-mode-float .tracy-inner.tracy-DumpPanel {
		max-width: 100%;
	}
	.tracy-inner .remote-api img {
		vertical-align: middle;
		position: relative;
		top: -1px;
		margin-right: 3px !important;
	}
</style>


<h1>API Requests</h1>

<div class="tracy-inner tracy-DumpPanel">

<table>
<?php foreach ($this->data as $my => $item): ?>
	<?php $class	=	'success' . ( $i++ % 2 ? ' tracy-alt' : '' ); ?>
	<tr class="<?php echo $class ?>">
		<td width="15"><?php echo $cnt++ ?>) </td><td>
		<td width="25"><?php echo $item['method'] ?></td>
		<td><?php echo $item['call'] ?></td>
		<td>
			<a href="#post<?php echo $cnt?>" class="tracy-toggle-collapsed">Variables</a>
			<a href="#optn<?php echo $cnt?>" class="tracy-toggle-collapsed">Curl Options</a>
		</td>
		<td>
			<a href="#result<?php echo $cnt?>" class="tracy-toggle-collapsed">Response</a>
		</td>
		<td>
			<a href="#curl<?php echo $cnt?>" class="tracy-toggle-collapsed">Curl Info</a>
		</td>
		<td class="remote-api">
			<?php if ( $item['debug'] ) : ?>
			<?php foreach ( $item['debug'] as $k => &$ri ) :
				if (! $ri->tab && !$ri->panel ) { unset( $item['debug'][$k] ); continue; }
				if ( $ri->tab && ! $ri->panel ) { echo ' ' . $ri->tab; unset( $item['debug'][$k] ); continue; }
				if (! $ri->tab && $ri->panel ) { unset( $item['debug'][$k] ); continue; }
				?>
				&nbsp;<a href="#remote<?php echo $my . $ri->id ?>" class="tracy-toggle-collapsed"><?php echo $ri->tab ?></a>
				
			<?php endforeach; ?>
			<?php endif; ?>
		</td>
	</tr>
	<tr class="<?php echo $class ?>">
		<td width="15">&nbsp;</td>
		<td colspan="7">
			<div style="display: none; max-width: 500px; " id="post<?php echo $cnt ?>"><pre><?php echo print_r($item['post'],1) ?></pre></div>
			<div style="display: none; max-width: 500px; " id="optn<?php echo $cnt ?>"><pre><?php echo print_r($item['optns'],1) ?></pre></div>
			<div style="display: none; max-width: 500px; " id="result<?php echo $cnt ?>"><?php echo ( is_bool( $item['result'] ) ? var_dump( $item['result'] ) : $item['result'] ) ?></div>
			<div style="display: none; max-width: 500px; " id="curl<?php echo $cnt ?>"><pre><?php echo print_r($item['curlinfo'],1) ?></pre></div>
			
			<?php if ( $item['debug'] ) : ?>
			<?php foreach ( $item['debug'] as $k => &$ri ) : ?>
				<div style="display: none; " id="remote<?php echo $my . $ri->id ?>"><?php echo $ri->panel ?></div>
			<?php endforeach; ?>
			<?php endif; ?>
		</td>
	</tr>
<?php endforeach ?>
</table>
</div>
<div class=" tracy-panel  tracy-mode-peek" id="tracy-debug-panel-test1">Hi There</div>