<?php

/* Bootstrap! */
require dirname( dirname( __DIR__ ) ) . DIRECTORY_SEPARATOR . 'bootstrap.php';


/**
 * Test class for DunUpdates.
 * Generated by PHPUnit on 2013-10-17 at 09:35:01.
 */
class DunUpdatesTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var DunUpdates
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    	get_dunamis();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers DunUpdates::getInstance
     */
    public function testGetInstance()
    {
    	$update		=	dunloader( 'updates' );
    	$this->assertTrue( $update !== null, 'Loader did not return an object' );
    	$this->assertTrue( is_object( $update ) );
    	$this->assertInstanceOf( 'DunUpdates', $update );
    	return $update;
    }
    
    
	/**
	 * @covers DunUpdates::__call
	 * @depends testGetInstance
	 */
	public function testSetVariable( $update )
	{
		$update->setTarget( 'value' );
		$update->setTest( 'test' );
		$this->assertAttributeContains( 'value', '_target', $update );
		$this->assertAttributeContains( 'test', '_test', $update );
		return $update;
	}
	
	
	/**
	 * @covers DunUpdates::__call
	 * @depends testSetVariable
	 */
	public function testHasVariable( $update )
	{
		$value = $update->hasTarget();
		$this->assertTrue( $value );
		
		$value = $update->hasTest();
		$this->assertTrue( $value );
		
		$this->assertFalse( $update->hasNothing() );
		return $update;
	}
	
	
	/**
	 * @covers DunUpdates::__call
	 * @depends testSetVariable
	 */
	public function testGetVariable( $update )
	{
		$value = $update->getTarget();
		$this->assertTrue( $value == 'value' );
		
		$value = $update->getTest();
		$this->assertTrue( $value == 'test' );
		return $update;
	}
	
	
    /**
     * @covers DunUpdates::getAdapters
     * @depends testGetInstance
     */
	public function testGetAdapters( $update )
	{
		$adapters = $update->getAdapters();
		$this->assertTrue( is_array( $adapters ) );
		$this->assertContains( 'curl', $adapters );
		
		return $adapters;
	}



    /**
     * @covers DunUpdates::downloadAndReturn
     * @depends testGetAdapters
     */
	public function testDownloadAndReturn( array $adapters )
	{
		$update	=	dunloader( 'updates' );
		$this->assertTrue(! is_bool( $update ) );
		$update->setUrl( 'https://www.gohigheris.com/downloads/dunamis-framework/v144/dunamis_whmcs_v1-4-4-zip?format=raw' );
		//$value	=	$update->downloadAndReturn( $update->getUrl(), array( 'username' => 'Steven', 'password' => 'J4VuMUaKnvwo9agtO3dx' ) ) ;
		$value	=	$update->downloadAndReturn( $update->getUrl(), array( 'dlid' => '7b340bd787b667127874dcf8e060a026' ) );
		$this->assertTrue( $update->getError() === null );
	}
	
	
	/**
	 * @covers DunUpdates::downloadAndStore
     * @depends testGetAdapters
	 */
	public function testDownloadAndStore( array $adapters )
	{
		$update	=	dunloader( 'updates' );
		$update->setUrl( 'https://www.gohigheris.com/downloads/dunamis-framework/v144/dunamis_whmcs_v1-4-4-zip?format=raw' );
		
		if ( isset( $_ENV['bamboo'] ) && $_ENV['bamboo'] == 'true' ) {
			$target	=	'/home/jwhmcsco/public_html/tmp/updatetest.tmp';
			$update->setTarget( '/home/jwhmcsco/public_html/hosting/tmp/updatetest.tmp' );
		}
		else {
			$target	=	'c:\xampp\tmp\update.tmp';
			$update->setTarget( 'c:\xampp\tmp\update.tmp' );
		}
		
		$value	=	$update->downloadAndStore( $update->getUrl(), $target, array( 'dlid' => '7b340bd787b667127874dcf8e060a026' ) ) ;
		$this->assertTrue( $value !== false, $update->getError() );
	}
	
	
	/**
	 * Call protected/private method of a class.
	 *
	 * @param object &$object    Instantiated object that we will run method on.
	 * @param string $methodName Method name to call
	 * @param array  $parameters Array of parameters to pass into method.
	 *
	 * @return mixed Method return.
	 */
	public function invokeMethod(&$object, $methodName, array $parameters = array())
	{
		$reflection = new \ReflectionClass(get_class($object));
		$method = $reflection->getMethod($methodName);
		$method->setAccessible(true);
	
		return $method->invokeArgs($object, $parameters);
	}
}
?>