<?php

/* Bootstrap! */
require dirname( dirname( __DIR__ ) ) . DIRECTORY_SEPARATOR . 'bootstrap.php';


/**
 * Test class for DunHooks.
 * Generated by PHPUnit on 2013-10-17 at 13:44:12.
 */
class DunHooksTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var DunHooks
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        get_dunamis();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

	
	/**
	 * @covers DunHooks::getInstance
	 */
	public function testGetInstance()
	{
        get_dunamis( 'dunamis' );
		$hooks	=	dunloader( 'hooks' );
		$this->assertTrue( $hooks !== null, 'Loader did not return an object' );
		$this->assertTrue( is_object( $hooks ) );
		$this->assertInstanceOf( 'DunHooks', $hooks );
		return $hooks;
	}
	
	
	/**
	 * @covers DunHooks::setExtension
	 * @depends testGetInstance
	 */
	public function testSetExtension( $hooks )
	{
		$hooks->setExtension( 'dunamis' );
		$this->assertAttributeContains( 'dunamis', 'extension', $hooks );
		return $hooks;
	}
	
	
	/**
	 * @covers DunHooks::getExtension
	 * @depends testSetExtension
	 */
	public function testGetExtension( $hooks )
	{
		$value = $hooks->getExtension();
		$this->assertTrue( $value == 'dunamis' );
	}
}
?>
