<?php


require dirname( dirname( __DIR__ ) ) . DIRECTORY_SEPARATOR . 'bootstrap.php';


/**
 * Test class for DunCurl.
 * Generated by PHPUnit on 2013-10-13 at 09:32:30.
 */
class DunCurlTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var DunCurl
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new DunCurl;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers DunCurl::__call
     * @todo Implement test__call().
     */
    public function test__call()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DunCurl::getInstance
     */
    public function testGetInstance()
    {
    	$instance	=	DunCurl :: getInstance();
    	
    	$this->assertInstanceOf( 'DunCurl', $instance );
    }

    /**
     * @covers DunCurl::_simple_call
     * @todo Implement test_simple_call().
     */
    public function test_simple_call()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DunCurl::simple_ftp_get
     * @todo Implement testSimple_ftp_get().
     */
    public function testSimple_ftp_get()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DunCurl::post
     * @todo Implement testPost().
     */
    public function testPost()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DunCurl::put
     * @todo Implement testPut().
     */
    public function testPut()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DunCurl::delete
     * @todo Implement testDelete().
     */
    public function testDelete()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DunCurl::set_cookies
     * @todo Implement testSet_cookies().
     */
    public function testSet_cookies()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DunCurl::has_errors
     * @todo Implement testHas_errors().
     */
    public function testHas_errors()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DunCurl::http_header
     * @todo Implement testHttp_header().
     */
    public function testHttp_header()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DunCurl::http_method
     * @todo Implement testHttp_method().
     */
    public function testHttp_method()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DunCurl::http_login
     * @todo Implement testHttp_login().
     */
    public function testHttp_login()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DunCurl::proxy
     * @todo Implement testProxy().
     */
    public function testProxy()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DunCurl::proxy_login
     * @todo Implement testProxy_login().
     */
    public function testProxy_login()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DunCurl::ssl
     */
    public function testSsl()
    {
    	$object	=	$this->object->ssl();
    	
        $this->assertInstanceOf( 'DunCurl', $object );
    }

    /**
     * @covers DunCurl::options
     */
    public function testOptions()
    {
    	$array	=	array( 'TIMEOUT' => '30', 'RETURNTRANSFER' => true );
    	$object	=	$this->object->options( $array );
    	
    	$this->assertInstanceOf( 'DunCurl', $object );
    }

    /**
     * @covers DunCurl::option
     */
    public function testOption()
    {
    	$object	=	$this->object->option( 'TIMEOUT', '30' );
    	$this->assertInstanceOf( 'DunCurl', $object );
    }

    /**
     * @covers DunCurl::create
     */
	public function testCreate()
	{
		$object	=	$this->object->create( 'https://www.gohigheris.com' );
		
		$this->assertInstanceOf( 'DunCurl', $object );
	}
	
	
    /**
     * @covers DunCurl::execute
     * @todo Implement testExecute().
     */
    public function testExecute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DunCurl::is_enabled
     */
    public function testIs_enabled()
    {
    	$this->assertTrue( is_bool( $this->object->is_enabled() ) );
    }

    /**
     * @covers DunCurl::debug
     */
    public function testDebug()
    {
    	ob_start();
    	$this->object->debug();
    	$result	=	ob_get_contents();
    	ob_end_clean();
    	
    	$this->assertStringStartsWith( "=============================================", $result );
    }

    /**
     * @covers DunCurl::debug_request
     */
	public function testDebug_request()
	{
		$debug = $this->object->debug_request();
		$this->assertArrayHasKey( 'url', $debug );
	}
}
?>
