<?php

// Bamboo testing
if ( isset( $_ENV['bamboo'] ) && $_ENV['bamboo'] == 'true' ) {
	require_once '/opt/atlassian/bamboo/Software/Dunamis/dunamis/core/curl.php';
}
else {
	require_once 'C:\xampp\www\mods\whmcs\includes\dunamis\core\curl.php';
}


/**
 * Test class for DunObject.
 * Generated by PHPUnit on 2013-10-13 at 20:27:56.
 */
class DunObjectTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var DunObject
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new DunObject;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
?>
