<?php

//
//	Admin Configuration Translations
//			WHMCS > Addon Modules
//	------------------------------------------------------------------------
$lang['config.title']			= 'Dunamis Framework';
$lang['config.author']			= '<div style="text-align: center; width: 100%; ">Go Higher<br/>Information Services, LLC</div>';
$lang['config.description']		= 'This is the core framework used by the next generation of WHMCS modules!';

$lang['config.debugerrors']				= '<h4>Enable Debugging</h4>';
$lang['config.debugerrors.selection']	= 'Yes,No';
$lang['config.debugerrors.desc']		= '<p>Enable this to display errors on your site captured by Dunamis.<br/><em>Note: This will also display any errors, warnings and notices generated by other addons and WHMCS itself.</em></p>';

$lang['config.errorlevel']				= '<h4>Error Reporting</h4>';
$lang['config.errorlevel.selection']	= 'None,Error,Warning,Notice';
$lang['config.errorlevel.desc']			= '<p>Select the level of error reporting to display:
<ul>
<li><strong>None</strong> will display no errors</li>
<li><strong>Error</strong> will display only errors received that normally cause the system to halt.</li>
<li><strong>Warning</strong> will display Errors and will display warning messages generated by PHP.</li>
<li><strong>Notice</strong> will display Errors and Warnings and will display programming errors</li>
</ul>
<br/><em>Note: This will also display any errors, warnings and notices generated by other addons and WHMCS itself.</em></p>';

$lang['admin.title']			= 'Dunamis Framework <small>%s</small>';

$lang['admin.title.home']		= 'Homepage';
$lang['admin.title.updates']	= 'Updates';
$lang['admin.title.installer']	= 'Installer';

$lang['admin.navbar.home']		= 'About';
$lang['admin.navbar.updates']	= 'Updates';
$lang['admin.navbar.installer']	= 'Installer';

$lang['home.subtitle']			=	'<h2>Welcome!</h2>';
$lang['home.body']	= '
<p>Thank you for installing the Dunamis Framework for WHMCS!  The Dunamis Framework is a continuing project to create a rapid deployment platform for multiple applications using consistant methods and techniques.</p>
<h3>What does <em>Dunamis</em> mean?</h3>
<p>In Greek, the word dunamis means explosive; it is literally the origin of the word dynamite.  We chose dunamis as the name of this framework because we hope and expect deployments of new products and ideas for multiple platforms to literally explode onto the marketplace!</p>
<h3>Is <em>Dunamis</em> free?  Can I use it for my projects?</h3>
<p>Dunamis is being released as an open sourced project under the GPL2 license but is not currently documented or supported.  You are welcome to use and modify, and we are working to have the project posted on git asap.</p>
<h3>Does it DO anything in WHMCS?</h3>
<p>While it may appear that the Dunamis Framework is not doing anything, it is provided as an addon so that future updates and releases will be easy to track.  In addition, there are more core functionality that will be added in over time including the ability to check for and notify for module updates and provide an installation location for those modules utilizing the Dunamis Framework.</p>
';

$lang['updates.subtitle']			=	'<h2>Coming Soon!</h2>';
$lang['updates.body']	= '
<p>This feature has not yet been implemented but is in the development stage.</p>
';

$lang['installer.subtitle']			=	'<h2>Coming Soon!</h2>';
$lang['installer.body']	= '
<p>This feature has not yet been implemented but is in the development stage.</p>
';
